In [45]:
import pandas as pd
import numpy as np

In [46]:
target_col = [2,3]
target_col

[2, 3]

In [47]:
df = pd.read_excel('./data/expand_mini.xlsx')

In [48]:
df

측정날짜 측정소명    수온  수소이온농도  전기전도도  용존산소   탁도  총유기탄소    총질소  \
0   2019.01.01 00:00   가평   2.8     6.8   97.0  12.6  0.5    1.4  1.771   
1   2019.01.01 01:00   가평   2.8     6.8   97.0  12.6  0.6    1.4  1.812   
2   2019.01.01 02:00   가평   NaN     NaN    NaN  12.6  0.4    1.4  1.765   
3   2019.01.01 03:00   가평   2.7     6.8   97.0  12.6  0.5    1.4  1.775   
4   2019.01.01 04:00   가평   NaN     NaN    NaN   NaN  NaN    NaN    NaN   
5   2019.01.01 05:00   가평   1.0    21.0   41.0  12.5  0.4    1.4  1.805   
6   2019.01.01 06:00   가평   2.0    22.0   42.0  12.5  0.5    1.4  1.793   
7   2019.01.01 07:00   가평   3.0    23.0   43.0  12.5  0.4    1.4  1.752   
8   2019.01.01 08:00   가평   NaN     NaN    NaN  12.5  0.4    1.4  1.789   
9   2019.01.01 09:00   가평   4.0    24.0   44.0  12.6  0.4    1.4  1.792   
10  2019.01.01 10:00   가평   5.0    25.0   45.0  12.7  0.5    1.4  1.794   
11  2019.01.01 11:00   가평   6.0    26.0   46.0  12.7  0.4    1.4  1.823   
12  2019.01.01 12:00   가평   7.0    27.0   47.0  12.7  0.4    1.4  1.829   
13  2019.01.01 13:00   가평   8.0    28.0   48.0  12.5  0.4    1.4  1.793   
14  2019.01.01 14:00   가평   NaN     NaN    NaN   NaN  NaN    NaN    NaN   
15  2019.01.01 15:00   가평   9.0    29.0   49.0  12.5  0.4    1.4  1.764   
16  2019.01.01 16:00   가평  10.0    30.0   50.0  12.5  0.5    1.4  1.782   
17  2019.01.01 17:00   가평  11.0    31.0   51.0  12.6  0.5    1.4  1.765   
18  2019.01.01 18:00   가평  12.0    32.0   52.0  12.5  0.4    1.4  1.761   
19  2019.01.01 19:00   가평  13.0    33.0   53.0  12.5  0.5    1.3  1.749   

       총인  클로로필-a  미생물_독성지수  
0   0.004     3.8       4.5  
1   0.005     4.1       2.5  
2   0.003     3.8       1.0  
3   0.005     3.9       1.0  
4     NaN     NaN       NaN  
5   0.002     3.7       2.5  
6   0.003     3.8       0.9  
7   0.002     3.8      -1.2  
8   0.002     3.7      -0.3  
9   0.001     3.4      -0.4  
10  0.003     3.3      -0.5  
11  0.003     2.4      -0.2  
12  0.005     1.9       0.2  
13  0.004     2.3      -2.6  
14    NaN     NaN       NaN  
15  0.003     2.6      -0.2  
16  0.002     3.8      -1.0  
17  0.004     4.0      -0.3  
18  0.005     4.0       1.7  
19  0.003     4.1       1.6

In [49]:
origin_df = df.iloc[:, target_col]
origin_df

수온  수소이온농도
0    2.8     6.8
1    2.8     6.8
2    NaN     NaN
3    2.7     6.8
4    NaN     NaN
5    1.0    21.0
6    2.0    22.0
7    3.0    23.0
8    NaN     NaN
9    4.0    24.0
10   5.0    25.0
11   6.0    26.0
12   7.0    27.0
13   8.0    28.0
14   NaN     NaN
15   9.0    29.0
16  10.0    30.0
17  11.0    31.0
18  12.0    32.0
19  13.0    33.0

In [51]:
len(origin_df)

20

In [50]:
input_unit_time = 3 # 최소 2

In [52]:
concat_list = []
for n in range(0, len(origin_df)-input_unit_time+1):
    split_df = origin_df[n:input_unit_time+n]
    print(split_df)
    concat_list.append(split_df)

    수온  수소이온농도
0  2.8     6.8
1  2.8     6.8
2  NaN     NaN
    수온  수소이온농도
1  2.8     6.8
2  NaN     NaN
3  2.7     6.8
    수온  수소이온농도
2  NaN     NaN
3  2.7     6.8
4  NaN     NaN
    수온  수소이온농도
3  2.7     6.8
4  NaN     NaN
5  1.0    21.0
    수온  수소이온농도
4  NaN     NaN
5  1.0    21.0
6  2.0    22.0
    수온  수소이온농도
5  1.0    21.0
6  2.0    22.0
7  3.0    23.0
    수온  수소이온농도
6  2.0    22.0
7  3.0    23.0
8  NaN     NaN
    수온  수소이온농도
7  3.0    23.0
8  NaN     NaN
9  4.0    24.0
     수온  수소이온농도
8   NaN     NaN
9   4.0    24.0
10  5.0    25.0
     수온  수소이온농도
9   4.0    24.0
10  5.0    25.0
11  6.0    26.0
     수온  수소이온농도
10  5.0    25.0
11  6.0    26.0
12  7.0    27.0
     수온  수소이온농도
11  6.0    26.0
12  7.0    27.0
13  8.0    28.0
     수온  수소이온농도
12  7.0    27.0
13  8.0    28.0
14  NaN     NaN
     수온  수소이온농도
13  8.0    28.0
14  NaN     NaN
15  9.0    29.0
      수온  수소이온농도
14   NaN     NaN
15   9.0    29.0
16  10.0    30.0
      수온  수소이온농도
15   9.0    29.0
16  10.0    30.0
17  11.0    31.0


In [54]:
output_df = pd.concat(concat_list)
output_df

수온  수소이온농도
0    2.8     6.8
1    2.8     6.8
2    NaN     NaN
1    2.8     6.8
2    NaN     NaN
3    2.7     6.8
2    NaN     NaN
3    2.7     6.8
4    NaN     NaN
3    2.7     6.8
4    NaN     NaN
5    1.0    21.0
4    NaN     NaN
5    1.0    21.0
6    2.0    22.0
5    1.0    21.0
6    2.0    22.0
7    3.0    23.0
6    2.0    22.0
7    3.0    23.0
8    NaN     NaN
7    3.0    23.0
8    NaN     NaN
9    4.0    24.0
8    NaN     NaN
9    4.0    24.0
10   5.0    25.0
9    4.0    24.0
10   5.0    25.0
11   6.0    26.0
10   5.0    25.0
11   6.0    26.0
12   7.0    27.0
11   6.0    26.0
12   7.0    27.0
13   8.0    28.0
12   7.0    27.0
13   8.0    28.0
14   NaN     NaN
13   8.0    28.0
14   NaN     NaN
15   9.0    29.0
14   NaN     NaN
15   9.0    29.0
16  10.0    30.0
15   9.0    29.0
16  10.0    30.0
17  11.0    31.0
16  10.0    30.0
17  11.0    31.0
18  12.0    32.0
17  11.0    31.0
18  12.0    32.0
19  13.0    33.0

In [55]:
x = output_df.to_numpy()
x

array([[ 2.8,  6.8],
       [ 2.8,  6.8],
       [ nan,  nan],
       [ 2.8,  6.8],
       [ nan,  nan],
       [ 2.7,  6.8],
       [ nan,  nan],
       [ 2.7,  6.8],
       [ nan,  nan],
       [ 2.7,  6.8],
       [ nan,  nan],
       [ 1. , 21. ],
       [ nan,  nan],
       [ 1. , 21. ],
       [ 2. , 22. ],
       [ 1. , 21. ],
       [ 2. , 22. ],
       [ 3. , 23. ],
       [ 2. , 22. ],
       [ 3. , 23. ],
       [ nan,  nan],
       [ 3. , 23. ],
       [ nan,  nan],
       [ 4. , 24. ],
       [ nan,  nan],
       [ 4. , 24. ],
       [ 5. , 25. ],
       [ 4. , 24. ],
       [ 5. , 25. ],
       [ 6. , 26. ],
       [ 5. , 25. ],
       [ 6. , 26. ],
       [ 7. , 27. ],
       [ 6. , 26. ],
       [ 7. , 27. ],
       [ 8. , 28. ],
       [ 7. , 27. ],
       [ 8. , 28. ],
       [ nan,  nan],
       [ 8. , 28. ],
       [ nan,  nan],
       [ 9. , 29. ],
       [ nan,  nan],
       [ 9. , 29. ],
       [10. , 30. ],
       [ 9. , 29. ],
       [10. , 30. ],
       [11. ,

In [60]:
input_unit_time

3

In [61]:
len(target_col)

2

In [69]:
len(output_df)

54

In [74]:
# group_cnt = input_unit_time * len(target_col)
group_cnt = int(len(output_df) / 3)
group_cnt

18

In [75]:
x = x.reshape(18, -1)
x

array([[ 2.8,  6.8,  2.8,  6.8,  nan,  nan],
       [ 2.8,  6.8,  nan,  nan,  2.7,  6.8],
       [ nan,  nan,  2.7,  6.8,  nan,  nan],
       [ 2.7,  6.8,  nan,  nan,  1. , 21. ],
       [ nan,  nan,  1. , 21. ,  2. , 22. ],
       [ 1. , 21. ,  2. , 22. ,  3. , 23. ],
       [ 2. , 22. ,  3. , 23. ,  nan,  nan],
       [ 3. , 23. ,  nan,  nan,  4. , 24. ],
       [ nan,  nan,  4. , 24. ,  5. , 25. ],
       [ 4. , 24. ,  5. , 25. ,  6. , 26. ],
       [ 5. , 25. ,  6. , 26. ,  7. , 27. ],
       [ 6. , 26. ,  7. , 27. ,  8. , 28. ],
       [ 7. , 27. ,  8. , 28. ,  nan,  nan],
       [ 8. , 28. ,  nan,  nan,  9. , 29. ],
       [ nan,  nan,  9. , 29. , 10. , 30. ],
       [ 9. , 29. , 10. , 30. , 11. , 31. ],
       [10. , 30. , 11. , 31. , 12. , 32. ],
       [11. , 31. , 12. , 32. , 13. , 33. ]])

In [77]:
new_np = []
for n in range(0, len(x)):
    new = np.concatenate((x[n][::2], x[n][1::2]), axis=0)
    new_np.append(new)

In [78]:
new_np = np.array(new_np)
new_np

array([[ 2.8,  2.8,  nan,  6.8,  6.8,  nan],
       [ 2.8,  nan,  2.7,  6.8,  nan,  6.8],
       [ nan,  2.7,  nan,  nan,  6.8,  nan],
       [ 2.7,  nan,  1. ,  6.8,  nan, 21. ],
       [ nan,  1. ,  2. ,  nan, 21. , 22. ],
       [ 1. ,  2. ,  3. , 21. , 22. , 23. ],
       [ 2. ,  3. ,  nan, 22. , 23. ,  nan],
       [ 3. ,  nan,  4. , 23. ,  nan, 24. ],
       [ nan,  4. ,  5. ,  nan, 24. , 25. ],
       [ 4. ,  5. ,  6. , 24. , 25. , 26. ],
       [ 5. ,  6. ,  7. , 25. , 26. , 27. ],
       [ 6. ,  7. ,  8. , 26. , 27. , 28. ],
       [ 7. ,  8. ,  nan, 27. , 28. ,  nan],
       [ 8. ,  nan,  9. , 28. ,  nan, 29. ],
       [ nan,  9. , 10. ,  nan, 29. , 30. ],
       [ 9. , 10. , 11. , 29. , 30. , 31. ],
       [10. , 11. , 12. , 30. , 31. , 32. ],
       [11. , 12. , 13. , 31. , 32. , 33. ]])

In [44]:
type(new_np)

numpy.ndarray