In [1]:
import pandas as pd
import numpy as np

In [2]:
input = './data/normal.xlsx'

In [3]:
df = pd.read_excel(input)
df

수온  수소이온농도  전기전도도  용존산소  탁도  총유기탄소  총질소  총인  클로로필-a  미생물_독성지수
0   1       2      3     4   1      1    2   3       4         1
1   1       2      3     4   2      1    2   3       4         1
2   1       2      3     4   3      1    2   3       4         1
3   1       2      3     4   4      1    2   3       4         1
4   1       2      3     4   5      1    2   3       4         1

In [4]:
output_np = df.to_numpy()[:,2:]
output_np

array([[3, 4, 1, 1, 2, 3, 4, 1],
       [3, 4, 2, 1, 2, 3, 4, 1],
       [3, 4, 3, 1, 2, 3, 4, 1],
       [3, 4, 4, 1, 2, 3, 4, 1],
       [3, 4, 5, 1, 2, 3, 4, 1]], dtype=int64)

In [5]:
data = output_np
_, dim = data.shape
norm_data = data.copy()
min_val = np.zeros(dim)
max_val = np.zeros(dim)

In [6]:
print('dim = ', dim)
print('norm_data = ', norm_data)
print('min_val = ', min_val)
print('max_val = ', max_val)

dim =  8
norm_data =  [[3 4 1 1 2 3 4 1]
 [3 4 2 1 2 3 4 1]
 [3 4 3 1 2 3 4 1]
 [3 4 4 1 2 3 4 1]
 [3 4 5 1 2 3 4 1]]
min_val =  [0. 0. 0. 0. 0. 0. 0. 0.]
max_val =  [0. 0. 0. 0. 0. 0. 0. 0.]


In [7]:
np.nanmin(norm_data[:,0])

3

In [8]:
np.nanmin(norm_data[:,1])

4

In [9]:
norm_data[:,0]

array([3, 3, 3, 3, 3], dtype=int64)

In [10]:
norm_data[:,1]

array([4, 4, 4, 4, 4], dtype=int64)

In [13]:
norm_data[:,0] - np.nanmin(norm_data[:,0
                                    ])

array([0, 0, 0, 0, 0], dtype=int64)

In [ ]:
for i in range(dim):
    min_val[i] = np.nanmin(norm_data[:,i])
    norm_data[:,i] = norm_data[:,i] - np.nanmin(norm_data[:,i])
    max_val[i] = np.nanmax(norm_data[:,i])
    norm_data[:,i] = norm_data[:,i] / (np.nanmax(norm_data[:,i]) + 1e-6)
    
print('norm_data = ', norm_data)
print('min_val = ', min_val)
print('max_val = ', max_val)